export const KEYS = {
    oauth: 'oauth',
    token: 'token',
    getMe: 'getMe',
    login: 'login',
    locales: 'locales',
    translations: 'translations',
    organizations: 'organizations',
    organizationsListForSelect: 'organizationsListForSelect',
    organizationTypeLevel: 'organizationTypeLevel',
    organizationTypeMedical: 'organizationTypeMedical',
    organizationLegalForm: 'organizationLegalForm',
    organizationTypeService: 'organizationTypeService',
    organizationManagementForm: 'organizationManagementForm',
    organizationCountry: 'organizationCountry',
    organizationTerritory: 'organizationTerritory',
    organizationDepartments: 'organizationDepartments',
    organizationPositions: 'organizationPositions',
    organizationType: 'organizationType',
    practitionerRole: 'practitionerRole',
    practitioners: 'practitioners',
    roles: 'roles',
    persons: 'persons',
    patients: 'patients',
    nationality: 'nationality',
    citizenship: 'citizenship',
    gender: 'gender',
    identifierType: 'identifierType',
    addressUse: 'addressUse',
    episodeOfCares:'episodeOfCares',
    conditionSeverity:'conditionSeverity',
    icd10:'icd10',
    episodeOfCareStatus:'episodeOfCareStatus',
    encounters:'encounters',
    encounterClass:'encounterClass',
    encounterLocationStatus:'encounterLocationStatus',
    serviceType:'serviceType',
}